import React from "react";
import Head from "next/head";
import Ad from "@/components/ad/Ad";

export default function Home() {
  return (
    <>
      <Head>
        <title>ADIDAS ORIGINALS X OASIS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="title" content="Amigos en 4 patas - Ven y adopta una mascota"/>
        <meta name="description" content="Adopta mascotas las 24 hs del dia. Pedidos por el sitio web"/>
        <link rel="icon" href="/adidas.ico" />
      </Head>
      <main>
        <Ad/>

      </main>
    </>
  );
}
